removed the comment line

diff --git a/ci/dev/Jenkinsfile b/ci/dev/Jenkinsfile
--- a/ci/dev/Jenkinsfile
+++ b/ci/dev/Jenkinsfile
@@ -39,9 +39,12 @@ pipeline{
             steps{
                 script{
                     bat '''
-                    for /f "tokens=1" %%i in ('docker ps -q --filter "publish=9595"') do docker stop %%i
-                    for /f "tokens=1" %%i in ('docker ps -a -q --filter "publish=9595"') do docker rm %%i
-                    '''
+                                for /f "tokens=1" %%i in ('docker ps -q --filter "publish=9595"') do docker stop %%i
+                                for /f "tokens=1" %%i in ('docker ps -a -q --filter "publish=9595"') do docker rm %%i
+
+                                REM Run new container
+                                docker run -d -p 9595:9595 --name %APP_NAME% %DOCKER_IMAGE%
+                        '''
                 }
             }
         }
@@ -49,7 +52,7 @@ pipeline{
             steps{
                 script{
                     sleep(10)
-                    bat 'curl -f http://localhost:${APP_PORT}/actuator/health || echo "Health check faild but continuing"'
+                    bat 'curl -f http://localhost:%APP_PORT%/actuator/health || echo "Health check faild but continuing"'
                     echo "✅ DEV Deployment Successful!"
                     echo "🌐 Access DEV at: http://localhost:${APP_PORT}"
                 }
